### ISSUE TITLE
Openshift 4.6 Auto Update from 0.2.0 to 0.3.0 Operator fails

### ISSUE THREAD

**Issue by rviper** [nginxinc/nginx-ingress-operator#140]
Update failed with a "Failed: OwnNamespace InstallModeType not supported, cannot configure to watch own namespace"

also see attached screenshots:
<img width="1040" alt="Bildschirmfoto 2021-07-17 um 17 15 02" src="https://user-images.githubusercontent.com/450152/126041457-e7d29957-cc89-41c9-90ed-d77aea88600b.png">
<img width="1459" alt="Bildschirmfoto 2021-07-17 um 17 14 51" src="https://user-images.githubusercontent.com/450152/126041462-1f4baf55-6d51-4707-acd1-ba69b83d54d1.png">

any upgrade instructions or way to solve this?

thx

**Comment by itfabrik** [comment]
thanks!

**Comment by juliorcp** [comment]
@ciarams87,

I have the same problem here (auto-update failure) and I don't have an option to "uninstall operator". I have only the option "Delete ClusterServiceVersion". Since there are a lot of applications pointing to some of ingress controllers "managed" by the operator, if I delete the CSV, the resources will be kept?

Thank you!
