### ISSUE TITLE
Upgrade Nginx Ingress Operator's Operator SDK version

### ISSUE THREAD

**Issue by OchiengEd** [nginxinc/nginx-ingress-operator#19]
**Is your feature request related to a problem? Please describe.**
Yes. The operator is dependent on packages that may be deprecated such as [github.com/operator-framework/operator-sdk/pkg/k8sutil](github.com/operator-framework/operator-sdk/pkg/k8sutil) which is used to determine if the Nginx Ingress Operator is running locally or in a Kubernetes cluster.

I can put something together and create a PR.

**Describe the solution you'd like**
Upgrade packages removing any obsolete Golang modules and migrate to the recently released Operator SDK v1.

**Describe alternatives you've considered**
Replace obsolete Golang Modules and keep current Operator SDK version

**Additional context**
Staying on Golang modules that are no longer available may stifle developer/community contribution as they may not be able to modify, build and run the operator locally.

**Comment by Dean-Coakley** [comment]
Hi @OchiengEd 

We previously upgraded to `0.18` https://github.com/nginxinc/nginx-ingress-operator/commit/1f6b17ff1bf298d5edf9969deab6dcf4678c3bb2


This involved the updating of `apiVersion` of CRDs https://github.com/nginxinc/nginx-ingress-operator/commit/1f6b17ff1bf298d5edf9969deab6dcf4678c3bb2#diff-bd2ed44f74a230a7bd9191960980cb73R1

This led to our operator being rejected by RedHats certification process because it used OpenShift 4.4 in their pipelines to certify our operator. Ultimately, we had to downgrade again: https://github.com/nginxinc/nginx-ingress-operator/commit/f71a8b2ef4acfe881adb277de0ed4334aaf9fdaa .

Updating the `operator-sdk` is something I'd love to do, or accept a PR for, but we must remain in line with RedHats certification process.

I'll try reach out to RedHat to figure out next steps!

**Comment by OchiengEd** [comment]
Sounds good. I'll reach out in the Kubernetes slack to understand the challenges with the certification process.
